footer part has been designed
SDGPTeamX/PregRed pull request #8
Opened 2021-03-23 05:03 UTC by SomaskaranParamanantham

2021-03-23 06:09 UTC, UmeshikaMahaliyadda approved these changes
if you can move social media platforms into right side corner, it will look nice according to my view. Other than that, nice code.

2021-03-24 10:20 UTC, Nisheanthan commented on pregred-gui/src/app/components/app-footer/AppFooter.js
> +
only leave one line space between imports and function

2021-03-24 10:22 UTC, Nisheanthan commented on pregred-gui/src/app/components/app-footer/AppFooter.js
> +        <div className="f-text">
be more specific on CSS class names. 'dot' and 'f-text' are not understandable. if it is footer text, name that as footer-text.

2021-03-24 10:25 UTC, Nisheanthan commented on pregred-gui/src/app/components/app-footer/AppFooter.js
> +            <p >Social  follows</p>
Social follows - what does this mean? focus on whether the content makes sense. 
moreover, are we going to link facebook, insta, linked in profiles here? if not remove them.

2021-03-24 10:26 UTC, Nisheanthan commented on pregred-gui/src/app/components/app-footer/AppFooter.js
> +            <li>Contact Us: 0768660203</li>
As i know, About Us and Contact Us  are going to navigate to respective pages. so, 'www.pregred.com' and mobile numbers are not needed.

2021-03-24 10:27 UTC, Nisheanthan commented on pregred-gui/src/app/components/app-footer/AppFooter.css
> +  background-color: #000000;
Can you make this bg colour similar to the navbar background colour?. its a variety of dark blue.

2021-03-24 10:28 UTC, Nisheanthan requested changes
Changes to be done

2021-03-27 07:21 UTC, merged